### ISSUE TITLE
GridLayout classic does not scroll inside flow VerticalLayout

### ISSUE THREAD

**Issue by Michael-OTS** [vaadin/classic-components#1]
Ist just a VerticalLayout with a H1 as header, the GridLayout and a FormLayout below.

If you scroll you can see, that the GridLayout remains static, only the H1 and the FormLayout take part in scrolling.

`
VerticalLayout vLayout = new VerticalLayout();
		vLayout.add(new H1("Some Header Above"));
		
		GridLayout gridLayout = new GridLayout(5, 5);
		for (int row = 0; row < gridLayout.getRows(); row++) {
			TextField text = new TextField("GridLayoutRow " + row);
			gridLayout.addComponent(text, 0, row);
		}
		
		FormLayout formLayout = new FormLayout();
		formLayout.setResponsiveSteps(new ResponsiveStep("0", 2));
		for (int i = 0; i < 30; i++) {
			TextField text = new TextField("FormLayout " + i);
			formLayout.add(text);
		}
		
		vLayout.add(gridLayout);
		vLayout.add(formLayout);

`

**Comment by sosa-vaadin** [comment]
Thanks for reaching out to us about this issue. The problem has to do with the GridLayout's default `position`. I adjusted it so it is now `relative` and made a few other fixes related to positioning. The contents of the GridLayout now scroll along with the rest of the dialog.

This will be released in the next patch release of Classic Components next week.
