### ISSUE TITLE
GridLayout miscalculates space between children

### ISSUE THREAD

**Issue by rodolforfq** [vaadin/classic-components#3]
When using GridLayout (com.vaadin.classic.v8.ui.GridLayout) with Vaadin 24, excessive space is introduced between children components. This doesn't seem to affect divs (if used as the children), but can be seen when using TextFields, for instance.

This happens even when spacing is set to false.

Tested with the following versions:
 - Classic Components: 24.2.1
 - Vaadin: 24.3.8

Minimal reproducible example:
```java
GridLayout gridLayout = new GridLayout(1, 1);
gridLayout.setSpacing(false);
for (int i = 0; i < 5; i++) {
  TextField field = new TextField();
  field.setLabel("field " + i);
  gridLayout.add(field);
}
```

When using the DOM inspector, TextFields seem to have a normal size, but the computed height of the container slot is significantly larger:
![image](https://github.com/user-attachments/assets/c92cf2f4-18fb-46d5-9ca9-d790c8364e45)

**Comment by szolo** [comment]
@rodolforfq please use Classic Components **24.2.2**
