### ISSUE TITLE
Panel doesn't display expected vertical scroll

### ISSUE THREAD

**Issue by paodb** [vaadin/classic-components#6]
I have a class extending Vertical Layout that has height set as full and I add a Panel also with full height and the Panel 
shows a vertical scroll as expected. But then if I add another component to the class, for example a Label before the Panel, then the Panel stops showing the expected vertical scroll. If I inspect the dom, the div representing the panel has height 100% but the parent v-slot it does not. If I set height 100% to this slot, the Panel shows the vertical scroll again but it goes out of the visible window as it seems it does not calculate correctly that the view also contains another component.

#### Minimal reproducible example
```java
import com.vaadin.classic.v8.ui.Label;
import com.vaadin.classic.v8.ui.Panel;
import com.vaadin.classic.v8.ui.VerticalLayout;
import com.vaadin.flow.router.Route;

@Route("panel-test")
public class MainView extends VerticalLayout {
    
    public MainView() {
		this.setSizeFull();
		add(new Label("just a label"));
                Panel panel = new Panel();
		VerticalLayout layout = new VerticalLayout();
		for(int i=0;i<100;i++){
			layout.add(new Label(i+" item"));
		}
		panel.setContent(layout);
		panel.setSizeFull();
		add(panel);
    }
}
```
![panel_02](https://github.com/user-attachments/assets/3a3051f9-62c0-4d22-b105-c32a1ec7ea62)

- Versions:
    - Vaadin : 23.5.2
    - Classic Components: 23.3.1

**Comment by szolo** [comment]
Fixed.
